Select job from emp where deptno = 10
Union
Select job from emp where deptno = 30;

SELECT E.ENAME, D.DNAME
FROM EMP E CROSS JOIN DEPT D;

SELECT E.ENAME, D.DNAME,e.deptno,d.deptno
FROM EMP E inner JOIN DEPT D on e.deptno = d.deptno; 
 select * from emp
 select * from dept
 
 SELECT E.ENAME, D.DNAME
FROM EMP E JOIN DEPT D USING (DEPTNO); 

SELECT E.ENAME, D.DNAME
FROM EMP E LEFT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO);

--Chương 8. CÁC LỆNH THAO TÁC DỮ LIỆU 
--1. Thêm dữ liệu vào bảng PROJECTS. 
select * from PROJECT_HUYEN
INSERT INTO PROJECT_HUYEN (PROJID, P_DESC,P_END_DATE,P_START_DATE,BUDGET_AMOUNT,MAX_NO_STAFF )
VALUES (1, 'WRITE C030 ', '07-JAN-88','02-JAN-88 ',500,1)

INSERT INTO PROJECT_HUYEN (PROJID, P_DESC,P_END_DATE,P_START_DATE,BUDGET_AMOUNT,MAX_NO_STAFF )
VALUES(2, 'PROOF READ NOTES','10-JAN-89', '01-JAN-89 ',600,1);

--2. Thêm dữ liệu vào bảng ASSIGNMENTS. 
INSERT INTO ASSIGNMENTS_HUYEN (PROJID, EMPNO ,A_START_DATE,A_END_DATE,BILL_RATE,ASSIGN_TYPE,HOURS )
VALUES (2, 7844 , '01-JAN-89','10-JAN-89',45.50,'PF',30);

INSERT INTO ASSIGNMENTS_HUYEN (PROJID, EMPNO ,A_START_DATE,A_END_DATE,BILL_RATE,ASSIGN_TYPE,HOURS )
VALUES (1,7369,'01-JAN-88','03-JAN-88',50.00,'WR',15)

INSERT INTO ASSIGNMENTS_HUYEN (PROJID, EMPNO ,A_START_DATE,A_END_DATE,BILL_RATE,ASSIGN_TYPE,HOURS )
VALUES (1,7902,'04-JAN-88','07-JAN-88',55.00,'WR',20)


select * from ASSIGNMENTS_HUYEN

--3. Cập nhật trường ASIGNMENT_TYPE từ WT thành WR.
UPDATE ASSIGNMENTS_HUYEN e
set ASSIGN_TYPE = 'WT'
where e.ASSIGN_TYPE ='WR'

--4. Nhập thêm số liệu vào bảng ASSIGNMENTS. 
INSERT INTO ASSIGNMENTS_HUYEN (PROJID, EMPNO ,A_START_DATE,A_END_DATE,BILL_RATE,ASSIGN_TYPE,HOURS )
VALUES (2, 7844 , '01-DEC-88','10-DEC-89',45.50,'PF',40);

INSERT INTO ASSIGNMENTS_HUYEN (PROJID, EMPNO ,A_START_DATE,A_END_DATE,BILL_RATE,ASSIGN_TYPE,HOURS )
VALUES (1,7369,'06-JUN-88','09-JUN-88',50.00,'PF',12);

INSERT INTO ASSIGNMENTS_HUYEN (PROJID, EMPNO ,A_START_DATE,A_END_DATE,BILL_RATE,ASSIGN_TYPE,HOURS )
VALUES (2,7332,'07-SEP-85','08-SEP-88',55.00,'WT',10);


