--TẠO BẢNG NHÀ XUẤT BẢN
DROP table TTTHuyen_NHAXUATBAN(
	ID Number not null CONSTRAINT  PK_TTTHuyen_NHAXUATBAN PRIMARY KEY, 
	MA  VARCHAR2(4),
	TEN VARCHAR2(20),
	TRANGTHAI NUMBER(1) ,
	DIACHI VARCHAR2(50),
	MOTA VARCHAR2(50),
	CONSTRAINT UNQ_TTTHuyen_NHAXUATBAN_MA UNIQUE(MA)
	);
--TẠO BẢNG TÁC GIẢ
CREATE table TTTHuyen_TACGIA(
	ID Number not null CONSTRAINT  PK_TTTHuyen_TACGIA PRIMARY KEY, 
	MA  VARCHAR2(4),
	TEN VARCHAR2(50) ,
	SDT VARCHAR2(10) ,
	DIACHI VARCHAR2(50),
	MOTA VARCHAR2(50),
	CONSTRAINT UNQ_TTTHuyen_TACGIA_MA UNIQUE(MA)
	);

--TẠO BẢNG SÁCH
create table TTTHuyen_SACH(
	ID Number not null CONSTRAINT  PK_TTTHuyen_SACH PRIMARY KEY, 
	MA  VARCHAR2(4),
	TEN VARCHAR2(50) ,
	IDNXB NUMBER CONSTRAINT FK_TTTHuyen_NXB REFERENCES SCOTT.TTTHuyen_NHAXUATBAN(ID),
	IDTACGIA NUMBER CONSTRAINT FK_TTTHuyen_TACGIA REFERENCES SCOTT.TTTHuyen_TACGIA(ID),
	CHUDE VARCHAR2(20),
	NAMXUATBAN NUMBER(4),
	MOTA VARCHAR2(50),
	SOLUONGCONLAI NUMBER,
	SOLUONGDANGMUON NUMBER,
	TONGSOSACH NUMBER,
	CONSTRAINT UNQ_TTTHuyen_SACH_MA UNIQUE(MA)
	);
--TAO BẢNG BẠN ĐỌC
create table TTTHuyen_BANDOC(
	ID Number not null CONSTRAINT PK_TTTHuyen_BANDOC PRIMARY KEY, 
	MA  VARCHAR2(4),
	TEN VARCHAR2(50),
	SDT VARCHAR2(10),
	DIACHI VARCHAR2(50),
	NGAYSINH DATE,
	NGAYTAOTAIKHOAN DATE,
	HANG VARCHAR2(10),
	CONSTRAINT UNQ_TTTHuyen_BANDOC_MA UNIQUE(MA)
	);
--TẠO BẢNG MƯỢN SÁCH
CREATE table TTTHuyen_MUONSACH(
	ID Number not null CONSTRAINT PK_TTTHuyen_MUONSACH PRIMARY KEY, 
	IDBANDOC Number CONSTRAINT FK_TTTHuyen_BANDOC REFERENCES SCOTT.TTTHuyen_BANDOC(ID),
	IDSACH Number CONSTRAINT FK_TTTHuyen_SACH REFERENCES SCOTT.TTTHuyen_SACH(ID),
	SOLUONG Number,
	NGAYGIOMUON DATE,
	NGAYGIOTRA DATE,
	TRANGTHAI NUMBER,
	GHICHU  VARCHAR2(50) NULL
	)
	-- 1.	Viết script tạo cấu trúc các bảng. Đối với bảng Mượn Sách cần đánh partition trên trường ngày giờ mượn, và 2 local index: 1 index trên trường id bạn đọc, 1 index trên id sách. Tên indexes theo cấu trúc : TENBANG_IDX_TENTRUONG
    PARTITION BY RANGE(NGAYGIOMUON)
    (
    PARTITION NGAYGIOMUON_2020 VALUES LESS THAN(TO_DATE('30/12/2021','DD/MM/YYYY')),
    PARTITION NGAYGIOMUON_2021 VALUES LESS THAN(TO_DATE('30/12/2022','DD/MM/YYYY')),
    PARTITION NGAYGIOMUON_2022 VALUES LESS THAN(TO_DATE('30/12/2023','DD/MM/YYYY'))
    );
     --INDEX
CREATE INDEX TTTHUYEN_BANDOC_IDX_IDBANDOC
ON TTTHuyen_BANDOC(ID);

CREATE INDEX TTTHUYEN_SACH_IDX_IDSACH
ON TTTHuyen_SACH(ID);

--2.Viết script tạo sequence cho mỗi bảng. Sequence được dùng để insert trường Id cho các bảng. Tên sequence theo cấu trúc : TENBANG_SEQ

CREATE SEQUENCE TTTHuyen_NHAXUATBAN_sequence
      INCREMENT BY 1
      START WITH 1
      MAXVALUE 10000
      NOCYCLE;
CREATE SEQUENCE TTTHuyen_TACGIA_sequence
      INCREMENT BY 1
      START WITH 1
      MAXVALUE 1000
      NOCYCLE;
 CREATE SEQUENCE TTTHuyen_SACH_sequence
      INCREMENT BY 1
      START WITH 1
      MAXVALUE 10000
      NOCYCLE;
 CREATE SEQUENCE TTTHuyen_BANDOC_sequence
      INCREMENT BY 1
      START WITH 1
      MAXVALUE 100000
      NOCYCLE;
CREATE SEQUENCE TTTHuyen_MUONSACH_sequence
      INCREMENT BY 1
      START WITH 1
      MAXVALUE 100000
      NOCYCLE;


--4.Viết script insert dữ liệu mẫu cho tất cả các bảng.
INSERT INTO TTTHUYEN_NHAXUATBAN
(ID,MA,TEN,TRANGTHAI,DIACHI,MOTA )
VALUES
( 2,'0002','NGUYỄN VĂN B',0,'HÀ NỘI','ĐỊA CHỈ CŨ' ),
( 1,'0001','NGUYỄN VĂN A',1,'HÀ NỘI','ĐỊA CHỈ CŨ' );

INSERT INTO TTTHUYEN_TACGIA
(ID,MA,TEN,SDT,DIACHI,MOTA )
VALUES
( 2,'0002','NGUYỄN VĂN B','0321456987','HÀ NỘI','ĐỊA CHỈ CŨ' );
INSERT INTO TTTHUYEN_TACGIA
(ID,MA,TEN,SDT,DIACHI,MOTA )
VALUES
( 1,'0001','NGUYỄN VĂN A','0321456988','HÀ NỘI','ĐỊA CHỈ CŨ' );


INSERT INTO TTTHUYEN_SACH
(ID,MA,TEN,IDNXB,IDTACGIA,CHUDE,
NAMXUATBAN,MOTA,SOLUONGCONLAI,SOLUONGDANGMUON,TONGSOSACH )
VALUES
( 3,'0003','DORAEMON3','2','1','HOẠT HÌNH',
2020,'TRUYỆN TRANH',200,10,210 );

INSERT INTO TTTHUYEN_BANDOC
(ID,MA,TEN,SDT,DIACHI,
NGAYSINH,NGAYTAOTAIKHOAN,HANG)
VALUES
( 3,'0003','BAI VĂN MG','0321452000','HÀ NAM',
'20/MAR/2000','12/MAY/2022','VÀNG');


INSERT INTO TTTHUYEN_MUONSACH
(ID,IDBANDOC,IDSACH,SOLUONG,
NGAYGIOMUON,NGAYGIOTRA,TRANGTHAI,GHICHU)
VALUES
( 1,1,1,2,
'11/AUG/2022','12/AUG/2022',1,'SÁCH ĐÃ ĐƯỢC TRẢ');

--5.Hiển thị dách sách tác giả và tổng số lượng sách của tác giả gồm các trường thông tin:
--Mã Tác Giả, Tên Tác Giả, Chủ Đề, Số Lượng Sách
--Sắp xếp theo số lượng sách giảm dần.

SELECT TG.MA AS MA_TG, TG.TEN AS TEN_TG, S.CHUDE, S.TONGSOSACH
FROM TTTHUYEN_TACGIA TG ,TTTHUYEN_SACH S 
WHERE TG.ID = S.IDTACGIA
ORDER BY S.TONGSOSACH DESC;

--6.Hiển thị 10 quyển sách có số lượng được mượn nhiều nhất gồm các trường thông tin:
--Mã Sách, Tên Sách, Tên Nhà Xuất Bản, Tên Tác Giả, Chủ Đề, Năm Xuất Bản, Số Lượng Còn Lại, Số Lượng Đã Mượn, Tổng Số
SELECT S.MA AS MA_SACH, S.TEN AS TEN_SACH,TG.TEN AS TEN_TG, S.CHUDE, S.NAMXUATBAN, S.SOLUONGCONLAI,S.SOLUONGDANGMUON, S.TONGSOSACH
FROM TTTHUYEN_SACH S , TTTHuyen_NHAXUATBAN NXB, TTTHUYEN_TACGIA  TG, TTTHUYEN_MUONSACH MS 
WHERE S.ID = MS.IDSACH AND S.IDNXB = NXB.ID AND S.IDTACGIA = TG.ID AND ROWNUM < 10 
order by S.TONGSOSACH desc

--7.	Hiển thị  thông tin bạn đọc và sách được mượn từ ngày đầu tháng hiện tại đến thời điểm hiện tại.
--Mã Bạn Đọc, Tên Bạn Đọc, Mã Sách, Tên Sách, Ngày Giờ Mượn, Số lượng
Sắp xếp theo ngày giờ mượn giảm dần, Tên bạn đọc tăng dần.

SELECT BD.MA AS MA_BAN_DOC, BD.TEN AS TEN_BAN_DOC, S.MA AS MA_SACH, S.CHUDE, S.NAMXUATBAN, S.SOLUONGCONLAI
FROM TTTHUYEN_BANDOC BD ,TTTHUYEN_SACH S, TTTHUYEN_MUONSACH MS
WHERE MS.IDBANDOC = BD.ID AND MS.IDSACH = S.ID AND MS.NGAYGIOMUON <= sysdate
ORDER BY MS.NGAYGIOMUON DESC

--8.	Hiển thị 10 quyển sách có số lượng được mượn nhiều nhất tính từ đầu năm 2022
--Mã Sách, Tên Sách, Số Lượng Đã Được Mượn.
SELECT S.MA AS MA_SACH, S.TEN AS TEN_SACH, MS.SOLUONG AS SO_LUONG_DA_MUON
FROM TTTHUYEN_SACH S INNER JOIN TTTHUYEN_MUONSACH MS ON S.ID = MS.IDSACH
WHERE ROWNUM < 11 
AND MS.SOLUONG >= (SELECT MAX(SOLUONG) FROM TTTHUYEN_MUONSACH
 					WHERE   NGAYGIOMUON>  '01/JAN/2022')
--9.	Hiển thị danh sách bạn đọc và số lần mượn sách tính từ đầu năm 2022 sắp xếp theo tên bạn đọc tăng dần:
--Mã Bạn Đọc, Tên Bạn Đọc, Số Lần Mượn
SELECT BD.MA AS MA_BAN_DOC, BD.TEN AS TEN_BAN_DOC, COUNT(BD.ID) AS SO_LAN_MUON
FROM TTTHUYEN_BANDOC BD INNER JOIN TTTHUYEN_MUONSACH MS ON BD.ID = MS.IDBANDOC
WHERE  MS.NGAYGIOMUON> '01/JAN/2022'
GROUP BY BD.MA,BD.TEN
ORDER BY BD.TEN ASC

--10.	Hiển thị thông tin bạn đọc gồm có:
--Mã Bạn Đọc, Tên Bạn Đọc, Tuổi (được tính dựa vào trường ngày sinh)
SELECT MA AS MA_BAN_DOC, TEN AS TEN_BAN_DOC, (TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(NGAYSINH,'YYYY'))AS TUOI
FROM TTTHUYEN_BANDOC 
--11.	Thống kê tổng số bạn đọc theo độ tuổi
--Tuổi, Tổng số Bạn Đọc
SELECT (TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(NGAYSINH,'YYYY'))AS TUOI, COUNT(MA) AS TONG_SO_BAN_HOC
FROM TTTHUYEN_BANDOC GROUP BY  (TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(NGAYSINH,'YYYY'))
--12.	Thống kê số lượng sách được xuất bản theo Nhà Xuất Bản, Theo năm xuất bản.
--Năm Xuất Bản, Mã Nhà Xuất Bản,Tên Nhà Xuất Bản, Số Lượng Sách
--Sắp xếp theo Năm xuất bản giảm dần, Tên Nhà xuất bản tăng dần.

SELECT DISTINCT S.NAMXUATBAN, NXB.MA AS MA_NXB, NXB.TEN AS TEN_NXB,SUM(S.TONGSOSACH)
FROM TTTHUYEN_NHAXUATBAN NXB INNER JOIN TTTHUYEN_SACH S ON S.IDNXB = NXB.ID
GROUP BY S.NAMXUATBAN,NXB.MA , NXB.TEN


--13.	Hiển thị 5 quyển sách được các bạn đọc có độ tuổi từ 18 đến 25 mượn nhiều nhất tính từ đầu năm 2022. (Tính theo trường số lượng mượn của sách)
--Mã Sách, Tên Sách, Số Lượng Được Mượn

SELECT S.MA AS MA_SACH, S.TEN AS TEN_SACH, SUM(S.SOLUONGDANGMUON) AS SO_LUONG_MUON
FROM TTTHUYEN_SACH S INNER JOIN TTTHUYEN_MUONSACH MS ON MS.IDSACH = S.ID,
 TTTHUYEN_MUONSACH MS INNER JOIN TTTHUYEN_BANDOC BD ON MS.IDBANDOC = BD.ID
WHERE AND MS.NGAYGIOMUON>=  '01/JAN/2022'and ROWNUM < 6 AND (TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(BD.NGAYSINH,'YYYY'))>=18 AND (TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(BD.NGAYSINH,'YYYY')) <=25 
GROUP BY S.TEN, S.MA
--14.	Hiển thị toàn bộ bạn đọc và sách mà bạn đọc đấy mượn, sẽ có bạn chưa mượn vẫn cần hiển thị và tên sách để là null.
--Mã bạn đọc, tên ban đọc, tên sách
SELECT 
FROM TTTHUYEN_SACH S INNER JOIN TTTHUYEN_MUONSACH MS ON MS.IDSACH = S.ID,
 TTTHUYEN_MUONSACH MS INNER JOIN TTTHUYEN_BANDOC BD ON MS.IDBANDOC = BD.ID